name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout репозитория
        uses: actions/checkout@v4

      - name: 🐳 Установка Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: 🔍 Проверка docker-compose.yml
        run: docker-compose config

      - name: 🏗️ Сборка Docker-образов
        run: docker-compose build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout репозитория
        uses: actions/checkout@v4

      - name: 🔑 Авторизация в GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 🏗️ Сборка и тегирование Docker-образа
        run: |
          IMAGE_NAME=ghcr.io/$(echo "prostoandr/ics")
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      - name: 🏗️ Сборка и публикация Docker-образа
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
